version: '3'

services:

  gossipbot:
      image: zhupengjia/gossipbot:cpu
      restart: always
      ports:
          - 5000:5000
      volumes:
          - ../data:/opt/chatbot/data
      working_dir: /opt/chatbot
      environment:
          MODEL_PATH:
          CONFIG_PATH:
          BOT_BACKEND: restful
