version: '2.3'

services:

  gossipbot:
      image: zhupengjia/gossipbot:gpu
      restart: always
      runtime: nvidia
      ports:
          - 5000:5000
      volumes:
          - /home/pzhu/data/dialog/dialogpt:/opt/chatbot/data
      working_dir: /opt/chatbot
      environment:
          NVIDIA_VISIBLE_DEVICES: all
          MODEL_PATH: /opt/chatbot/data/large_ft.pkl
          CONFIG_PATH: /opt/chatbot/data/762M/config.json
          BOT_BACKEND: restful
          DEVICE: "cuda:0"
