version: '3'

services:

  gossipbot:
      image: zhupengjia/gossipbot:cpu
      restart: always
      ports:
          - 5000:5000
      volumes:
          - /home/pzhu/data/dialog/dialogpt:/opt/chatbot/data
      working_dir: /opt/chatbot
      environment:
          MODEL_PATH: /opt/chatbot/data/large_ft.pkl
          CONFIG_PATH: /opt/chatbot/data/762M
          BOT_BACKEND: restful
